### ISSUE TITLE
接入deepl的免费api

### ISSUE THREAD

**Issue by garyvalue** [speauty/anto#9]
https://github.com/OwO-Network/DeepLX

**Comment by speauty** [comment]
感谢大佬，我这周就把这个接入咯

**Comment by garyvalue** [comment]
还有一些gpt接口，有兴趣研究吗
https://github.com/xiangsx/gpt4free-ts

**Comment by szz1233** [comment]
也请问是否可以添加使用谷歌云的api

**Comment by speauty** [comment]
> 也请问是否可以添加使用谷歌云的api

应该也是可以的，只是我刚去看了一下，似乎需要visa。。。什么来着
